### PR TITLE
Issue #31 - adding server ServiceLoader required lines

### PR DESCRIPTION
**Pull request by joakime**
Signed-off-by: Joakim Erdfelt <joakim.erdfelt@gmail.com>

### CODE REVIEW

**Comment by joakime** [comment]
If this is sane, we should make a version `1.1.2.1` release of this jar.

**Comment by joakime** [comment]
This fix is related to a report at https://github.com/eclipse/jetty.project/issues/4797

**Comment by olamy** [comment]
we might need this for jakarta namespace (jetty-11) as well  https://github.com/eclipse/jetty.toolchain/tree/master/jetty-jakarta-websocket-api

**Comment by janbartel** [comment]
@joakime  please take a look at the existing javax websocket osgi test here: https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/TestJettyOSGiBootWithJavaxWebSocket.java#L118

Notice that clearly at some point the javax.websocket-api jar didn't have osgi headers in the manifest, so I had to manually add those in. Notice also that the ServiceLoader is configured to find javax.websocket.ContainerProvider not javax.websocket.server.ServerEndpointConfig$Configurator. If the latter were needed, how can this test be working?

**Comment by joakime** [comment]
> Notice also that the ServiceLoader is configured to find javax.websocket.ContainerProvider not javax.websocket.server.ServerEndpointConfig$Configurator. If the latter were needed, how can this test be working?

@janb lets see if I can answer your questions ...

* `javax.websocket.ContainerProvider` is for client container access.
* `javax.websocket.server.ServerEndpointConfig$Configurator` is for the default server configurator.

They are different things.

Also, the OSGi tests don't actually test a custom Configurator, either on the Client endpoint or the Server endpoint.
See: https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-osgi/test-jetty-osgi/src/test/java/org/eclipse/jetty/osgi/test/SimpleJavaxWebSocket.java

**Review by janbartel — APPROVED** [review]
The change seems to work when run in jetty-10, so LGTM.

**Pull request merged**
